ecm: 240
intLumi: 10800000  # 10.8 /ab
apply_scaling: False  # rescale photon momentum resolution (default 3%)
scaling_factor: 0.33 # for rescaling the photon momentum resolution

inputDirBase: "/eos/experiment/fcc/ee/generation/DelphesEvents/winter2023/IDEA"
outputDir: "/eos/user/l/lherrman/FCC/Higgsgamma/outputs/"

processList: 
  mgp8_ee_ha:    {fraction: 1}
  wzp6_ee_bba:   {fraction: 1} #0.005
  wzp6_ee_cca:   {fraction: 1} #0.1
  wzp6_ee_qqa:   {fraction: 1}
  wzp6_ee_eea:   {fraction: 1}
  wzp6_ee_mumua: {fraction: 1}
  wzp6_ee_tautaua: {fraction: 1}
  p8_ee_WW:        {fraction: 1} # do NOT increase highter than 0.5 for HWW if you use the BDT! 0.005
  p8_ee_ZZ:        {fraction: 1} #0.02
  #mgp8_ee_zh:      {fraction: 1}

cuts:
  photon_iso_cone_radius_range: [0.01, 0.5]
  photon_iso_threshold: 0.2
  photon_energy_range: [60, 100] # why not 80 - 90? # broad cut needed for m recoil fitting range..
  photon_cos_theta_max: 0.9
  recoil_mass_range: [110, 150]
  recoil_mass_signal_range: [123.5, 126.5]
  min_n_reco_no_gamma: 15


  
   