ecm: 240
intLumi: 10800000  # 10.8 /ab
apply_scaling: False  # rescale photon momentum resolution (default 3%)
scaling_factor: 0.33



inputDirBase: "/eos/experiment/fcc/ee/generation/DelphesEvents/winter2023/IDEA"
outputDir: "outputs/"

processList:
  # p8_ee_Hgamma:    { crossSection: 8.20481e-05,  fraction: 1}
  mgp8_ee_ha:    { crossSection: 8.20481e-05,  fraction: 1}
  wzp6_ee_bba:   { crossSection: 2.35,  fraction: 1}
  wzp6_ee_cca:   { crossSection: 2.15,  fraction: 0.1}
  wzp6_ee_qqa:   { crossSection: 6.9, fraction: 0.1}
  # p8_ee_qqgamma:   { crossSection: 6.9, fraction: 1, inputDir: "/eos/user/l/lherrman/FCC/data/HiggsGamma"} # exchange this by the line above

  wzp6_ee_eea: { crossSection: 190,  fraction: 0.1}
  # p8_ee_eegamma:   { crossSection: 190,  fraction: 1, inputDir: "/eos/user/l/lherrman/FCC/data/HiggsGamma"}
  wzp6_ee_mumua: { crossSection: 0.8, fraction: 0.1}
  # p8_ee_mumugamma: { crossSection: 0.8, fraction: 1,  inputDir: "/eos/user/l/lherrman/FCC/data/HiggsGamma"}

  wzp6_ee_tautaua: { crossSection: 0.77, fraction: 1}
  # p8_ee_tautaugamma: { crossSection: 0.77, fraction: 1, inputDir: "/eos/user/l/lherrman/FCC/data/HiggsGamma"}
  p8_ee_WW:        {fraction: 0.5} # do NOT increase highter than 0.5 for HWW if you use the BDT!
  p8_ee_ZZ:        {fraction: 0.1}
  mgp8_ee_zh:      {crossSection: 0.2, fraction: 1} 
 

cuts:
  photon_iso_cone_radius_range: [0.01, 0.5]
  photon_iso_threshold: 0.2
  photon_energy_range: [60, 100] # why not 80 - 93? 
  photon_cos_theta_max: 0.9
  recoil_mass_range: [110, 150]
  recoil_mass_signal_range: [123.5, 126.5]
  min_n_reco_no_gamma: 5
