outputDir_sub: "qqlv"
do_inference: False
cuts:
  m_jj_range: [65, 87]  # W mass range cut
  pT_miss: 5  # min missing transverse momentum cut
  recoil_gammaqq_range: [10, 55]
  n_const_per_jet: 4  # number of constituents per jet cut
  WW_cos_theta_max: 0.9  # cos(theta_WW) cut
  pT_lepton: 7  # min lepton pT cut
