outputDir_sub:  ["lvqq_bin1", "lvqq_bin2"] 
do_inference: True # use BDT score: HWW vs WW
cuts:
  m_jj_range: [8, 55]  # W* mass range cut
  pT_miss: 15
  recoil_gammaqq_range: [70, 90]
  n_const_per_jet: 4  # number of constituents per jet cut
  mva_score_cut: {"bin1": [0.9, 0.997], "bin2": [0.997, 1]}  # BDT score cut, 0.99 is the best, do 0.9-0.997 and 0.997-1 for the two bin analysis
do_scan: True # do BDT score scan for two bins
scan:
  mva_score_cut: [0.901, 0.905, 0.91, 0.915, 0.92, 0.925, 0.93, 0.935, 0.94, 0.945, 0.95, 0.955, 0.96, 0.965, 0.97, 0.975, 0.98, 0.985, 0.986, 0.987, 0.988, 0.989, 0.99, 0.991, 0.992, 0.993, 0.994, 0.995, 0.996, 0.997, 0.998, 0.999]
  outputDir_sub: ["lvqq_x1_scan", "lvqq_09x_scan"]
