ecm: 160
intLumi: 19200000  # 19.2 /ab
apply_scaling: False  # rescale photon momentum resolution (default 3%)
scaling_factor: 0.33 # for rescaling the photon momentum resolution

inputDirBase: "/eos/experiment/fcc/ee/generation/DelphesEvents/winter2023/IDEA"
outputDir: "/eos/user/l/lherrman/FCC/Higgsgamma/outputs/"

processList:
  #mgp8_ee_ha:    {fraction: 1}
  #wzp6_ee_bba:   {fraction: 0.08}
  #wzp6_ee_cca:   {fraction: 1}
  #wzp6_ee_qqa:   {fraction: 1}
  #wzp6_ee_eea:   {fraction: 1}
  #wzp6_ee_mumua: {fraction: 1}
  #wzp6_ee_tautaua: {fraction: 1}
  #p8_ee_WW:        {fraction: 0.1} # do NOT increase highter than 0.5 for HWW if you use the BDT!
  p8_ee_ZZ:        {fraction: 0.01}
  #wzp6_ee_aqqW: {fraction: 1}
  #wzp6_ee_alnuW: {fraction: 1}
  # ZH ?
 
cuts:
  photon_iso_cone_radius_range: [0.01, 0.5]
  photon_iso_threshold: 0.2
  photon_energy_range: [20, 40] #[25, 32] # p(gamma) = 31.2 GeV
  photon_cos_theta_max: 0.9
  recoil_mass_range: [110, 150]
  recoil_mass_signal_range: [123.5, 126.5]
  min_n_reco_no_gamma: 5
