ecm: 240
intLumi: 10800000  # 10.8 /ab
apply_scaling: False  # rescale photon momentum resolution (default 3%)
scaling_factor: 0.33 # for rescaling the photon momentum resolution

inputDirBase: "/eos/experiment/fcc/ee/generation/DelphesEvents/winter2023/IDEA"
outputDir: "outputs/"

processList:
  # p8_ee_Hgamma:    { crossSection: 8.20481e-05,  fraction: 1, inputDir: "/eos/user/l/lherrman/FCC/data/HiggsGamma"}
  mgp8_ee_ha:    {fraction: 1}
  wzp6_ee_bba:   {fraction: 1}
  wzp6_ee_cca:   {fraction: 1}
  wzp6_ee_qqa:   {fraction: 1}
  wzp6_ee_eea:   {fraction: 1}
  wzp6_ee_mumua: {fraction: 1}
  wzp6_ee_tautaua: {fraction: 1}
  p8_ee_ZZ:        {fraction: 1}
  mgp8_ee_zh:      {fraction: 1}
  wzp6_ee_aqqW: {fraction: 0.85} # do NOT increase higher than 0.85 for HWW if you use the BDT!
  wzp6_ee_alnuW: {fraction: 0.96} # do NOT use more than 96% if BDT is used! 
  # p8_ee_WW:        {fraction: 0.5} # do NOT increase highter than 0.5 for HWW if you use the BDT!
  # wzp6_ee_WWa: {fraction: 0.5} # dataset vanishes...

cuts:
  photon_iso_cone_radius_range: [0.01, 0.5]
  photon_iso_threshold: 0.2
  photon_energy_range: [80, 90] # p(gamma) = 87.4 GeV
  photon_cos_theta_max: 0.9
  recoil_mass_range: [110, 150]
  recoil_mass_signal_range: [123.5, 126.5]
  min_n_reco_no_gamma: 5
