outputDir_sub: "exclusive_Hjj"
branching_ratios:
  B: 0.580
  G: 0.082
  TAU: 0.062
cuts:
  m_jj_range: {B: [100, 135], G: [100, 135]} # G: [118, 128]} test this! # Higgs
  sum_jetscores_min: {B: 1.03, G: 1.27}  # minimum sum of jet. Best values: B: 1.03, G: 1.33, TAU: ? 
